apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-openwebui-deployment
  labels:
    app: ollama-openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-openwebui
  template:
    metadata:
      labels:
        app: ollama-openwebui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
          env:
            - name: "HOST_DOCKER_INTERNAL"
              value: "host.docker.internal:host-gateway"
        - name: ollama
          image: ollama/ollama
          ports:
            - containerPort: 11434

---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
spec:
  selector:
    app: ollama-openwebui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama-openwebui
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP
